<?xml version="1.0" encoding="UTF-8"?><project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>com.spai</groupId><artifactId>sp-ai-portal-parent</artifactId><version>1.0.0</version></parent><artifactId>portal-task</artifactId><dependencies><dependency><groupId>com.spai</groupId><artifactId>portal-common</artifactId></dependency><dependency><groupId>com.spai</groupId><artifactId>portal-organization</artifactId></dependency><dependency><groupId>com.spai</groupId><artifactId>portal-security</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-data-jpa</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency></dependencies></project>
