package com.spai.portal.web;

import java.nio.charset.StandardCharsets;import java.util.*;import com.fasterxml.jackson.databind.*;import com.spai.portal.asset.domain.*;import com.spai.portal.asset.repository.*;import com.spai.portal.organization.domain.AppUser;import com.spai.portal.organization.repository.AppUserRepository;import com.spai.portal.task.domain.*;import com.spai.portal.task.repository.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.ApplicationArguments;import org.springframework.boot.ApplicationRunner;import org.springframework.core.io.ClassPathResource;import org.springframework.security.crypto.password.PasswordEncoder;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;

@Component public class BootstrapDataInitializer implements ApplicationRunner {
 private static final String[]TEAMS={"00000000-0000-0000-0000-000000000001","00000000-0000-0000-0000-000000000002","00000000-0000-0000-0000-000000000003"};private final boolean enabled;private final String adminName,adminPassword;private final ObjectMapper json;private final AppUserRepository users;private final PasswordEncoder passwords;private final AssetCategoryRepository categories;private final AssetRepository assets;private final DeliveryTaskRepository tasks;private final TaskProgressRepository progress;
 public BootstrapDataInitializer(@Value("${portal.bootstrap.enabled:false}")boolean enabled,@Value("${portal.bootstrap.admin-username:admin}")String adminName,@Value("${portal.bootstrap.admin-password:}")String adminPassword,ObjectMapper json,AppUserRepository users,PasswordEncoder passwords,AssetCategoryRepository categories,AssetRepository assets,DeliveryTaskRepository tasks,TaskProgressRepository progress){this.enabled=enabled;this.adminName=adminName;this.adminPassword=adminPassword;this.json=json;this.users=users;this.passwords=passwords;this.categories=categories;this.assets=assets;this.tasks=tasks;this.progress=progress;}
 @Override @Transactional public void run(ApplicationArguments args)throws Exception{if(!enabled)return;admin();if(categories.count()==0||assets.count()==0)portal();if(tasks.count()==0)tasks();}
 private void admin(){if(users.findByUsername(adminName).isPresent())return;AppUser u=new AppUser();u.setId(UUID.randomUUID().toString());u.setUsername(adminName);u.setPasswordHash(passwords.encode(adminPassword));u.setDisplayName("平台管理员");u.getRoles().add("ADMIN");users.save(u);}
 private void portal()throws Exception{JsonNode root=read("bootstrap/portal_data.json");Map<String,String>catIds=new HashMap<String,String>();for(JsonNode s:root.path("stages")){int stage=s.path("stage").asInt();int order=0;for(JsonNode c:s.path("subcategories")){String name=c.path("name").asText();String key=stage+"|"+name;String id=uuid("category:"+key);AssetCategory category=new AssetCategory();category.setId(id);category.setStageId(stage);category.setNumber(c.path("number").asText());category.setName(name);category.setExternalFolderId(c.path("folder_id").asText(null));category.setSortOrder(order++);categories.save(category);catIds.put(key,id);}}
  for(JsonNode n:read("bootstrap/search-data.json").path("files")){int stage=n.path("stage_num").asInt();String sub=n.path("sub_name").asText();String categoryId=catIds.get(stage+"|"+sub);if(categoryId==null){categoryId=uuid("category:"+stage+"|"+sub);AssetCategory c=new AssetCategory();c.setId(categoryId);c.setStageId(stage);c.setNumber(n.path("sub_number").asText());c.setName(sub);c.setSortOrder(999);categories.save(c);catIds.put(stage+"|"+sub,categoryId);}String media=n.path("media_id").isNull()?null:n.path("media_id").asText(null);if(media!=null&&assets.findByMediaId(media).isPresent())continue;Asset a=new Asset();a.setId(uuid("asset:"+(media==null?stage+"|"+sub+"|"+n.path("name").asText():media)));a.setName(n.path("name").asText());a.setType(n.path("type").asText());a.setStageId(stage);a.setCategoryId(categoryId);if("C".equals(a.getType()))a.setCaseCategoryId(com.spai.portal.asset.service.AssetService.classifyCase(a.getName()));a.setMediaId(media);a.setSourceUrl(n.path("direct_url").asText(null));a.setSearchText(a.getName()+" "+n.path("stage_name").asText()+" "+sub);assets.save(a);}}
 private void tasks()throws Exception{for(JsonNode n:read("bootstrap/tasks.json")){String external=n.path("id").asText();DeliveryTask t=tasks.findByExternalId(external).orElseGet(DeliveryTask::new);if(t.getId()==null)t.setId(uuid("task:"+external));t.setExternalId(external);t.setStage(n.path("stage").asText());t.setScene(n.path("scene").asText());t.setAi(n.path("ai").asText());t.setDescription(n.path("desc").asText());t.setInput(n.path("input").asText());t.setOutput(n.path("output").asText());t.setType(n.path("type").asText());t.setSkill(n.path("skill").asText());t.setPriority(n.path("pri").asText());t.setDifficulty(n.path("diff").asText());tasks.save(t);for(int i=0;i<3;i++){TaskProgress p=new TaskProgress();p.setId(uuid("progress:"+external+":"+i));p.setTaskId(t.getId());p.setTeamId(TEAMS[i]);String value=n.path("t"+(i+1)+"s").asText();p.setStatus(Arrays.asList("待创建","进行中","已完成").contains(value)?value:"待创建");progress.save(p);}}}
 private JsonNode read(String path)throws Exception{return json.readTree(new ClassPathResource(path).getInputStream());}private String uuid(String value){return UUID.nameUUIDFromBytes(value.getBytes(StandardCharsets.UTF_8)).toString();}
}
