package com.spai.portal.skill.controller;
import com.spai.portal.common.ApiResponse; import com.spai.portal.security.PortalPrincipal; import com.spai.portal.skill.service.CapabilityManagementService; import java.util.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.multipart.MultipartFile;
@RestController @RequestMapping("/api/v1/my/capabilities") public class EmployeeCapabilityController {
 private final CapabilityManagementService service; public EmployeeCapabilityController(CapabilityManagementService s){service=s;}
 @GetMapping public ApiResponse<List<Map<String,Object>>> list(@AuthenticationPrincipal PortalPrincipal p){if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); return ApiResponse.ok(service.myList(p.getUserId()));}
 @PostMapping("/import") public ApiResponse<Map<String,Object>> importDraft(@RequestPart String manifest,@RequestPart(value="package",required=false) MultipartFile pack,@RequestParam(required=false) String expectedUpdatedAt,@AuthenticationPrincipal PortalPrincipal p){if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); try { if (new com.fasterxml.jackson.databind.ObjectMapper().readTree(manifest).path("identity").path("slug").asText().equals("platform-skill-adapter")) throw new org.springframework.security.access.AccessDeniedException("该适配器仅管理员可操作"); } catch (org.springframework.security.access.AccessDeniedException e) { throw e; } catch (Exception e) { /* 统一由服务校验 JSON */ } return ApiResponse.ok(service.importManifest(manifest,pack,p.getUserId(),expectedUpdatedAt));}
 @GetMapping("/{assetId}/versions") public ApiResponse<List<Map<String,Object>>> history(@PathVariable String assetId,@AuthenticationPrincipal PortalPrincipal p){if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); return ApiResponse.ok(service.myHistory(assetId,p.getUserId()));}
 @GetMapping("/{assetId}/versions/{versionId}/audits") public ApiResponse<List<Map<String,Object>>> audit(@PathVariable String assetId,@PathVariable String versionId,@AuthenticationPrincipal PortalPrincipal p){if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); return ApiResponse.ok(service.myAudit(assetId,versionId,p.getUserId()));}
 @PostMapping("/{assetId}/versions/{versionId}/submit") public ApiResponse<Map<String,Object>> submit(@PathVariable String assetId,@PathVariable String versionId,@RequestBody Map<String,String> b,@AuthenticationPrincipal PortalPrincipal p){if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); return ApiResponse.ok(service.transition(assetId,versionId,"submit",b.get("reason"),b.get("expectedUpdatedAt"),p.getUserId()));}
 @GetMapping("/{assetId}/versions/{versionId}/download") public org.springframework.http.ResponseEntity<org.springframework.core.io.Resource> download(@PathVariable String assetId,@PathVariable String versionId,@AuthenticationPrincipal PortalPrincipal p)throws java.io.IOException {if(p==null) throw new org.springframework.security.access.AccessDeniedException("需要登录"); com.spai.portal.asset.service.FileStorageService.StoredFile f=service.myDownload(assetId,versionId,p.getUserId()); return org.springframework.http.ResponseEntity.ok().contentType(org.springframework.http.MediaType.APPLICATION_OCTET_STREAM).contentLength(f.metadata.getFileSize()).body(f.resource);}
}
